In [2]:
import numpy as np

In [3]:
a1 = np.array(['Python', 'R', 'Spark', 'Hadoop'])

In [6]:
a1

array(['Python', 'R', 'Spark', 'Hadoop'], dtype='<U6')

In [7]:
a2 = np.array([['Altura', 'Largura', 'Profundidade'], [55, 70, 90]])

In [8]:
a2

array([['Altura', 'Largura', 'Profundidade'],
       ['55', '70', '90']], dtype='<U12')

In [15]:
a3 = np.array([[10,20,30], [40,50, 60]])

In [10]:
a3

array([[10, 20, 30],
       [40, 50, 60]])

In [23]:
print(a1.shape)   # O primeiro valor é a quantidade de 'colchetes' e o segundo a quantidade de itens dentro do colchetes.
print(a2.shape)
print(a3.shape)

(4,)
(2, 3)
(2, 3)


In [20]:
a1.ndim   # Mostra quantas dimensões tem o array.

1

In [21]:
a2.ndim

2

In [22]:
a3.ndim

2

In [29]:
a3.max()  # Retorna o maior valor do array. OBS.: Não funciona com valores heterogeneos.

60

In [31]:
a3.min()  # Retorna o menor valor do array. OBS.: Não funciona com valores heterogeneos.

10

In [39]:
valores = np.arange(20)  # Gera um array com 20 valores. Pode ser usado no formato arange(inicio, fim, contador)
valores

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [44]:
matriz = np.linspace(0, 10, 20)  # Gera 20 elementos de 0 a 10.
matriz

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [48]:
matriz2 = np.linspace(0, 10, 5)  # O mesmo que o de cima.
matriz2

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

# Estruturas de Matrizes

In [53]:
matriz3 = np.zeros((10,10))
matriz3

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [56]:
matriz4 = np.ones((2,3))
matriz4

array([[1., 1., 1.],
       [1., 1., 1.]])

In [57]:
# NumPy EYE. Produz uma matriz do tipo Identity.
matriz5 = np.eye(10)
matriz5

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [59]:
matriz6 = np.diag((2, 4, 6, 8, 10, 12, 14, 16, 18, 20))
matriz6

array([[ 2,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  4,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  6,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  8,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 10,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0, 12,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0, 14,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0, 16,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0, 18,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0, 20]])

In [62]:
matriz7 = np.empty((10,5))
matriz7

array([[4.66349596e-310, 7.90505033e-323, 4.66349745e-310,
        6.89841907e-310, 6.89841918e-310],
       [6.89841907e-310, 0.00000000e+000, 4.66349744e-310,
        0.00000000e+000, 0.00000000e+000],
       [4.94065646e-324, 0.00000000e+000, 9.54898106e-313,
        0.00000000e+000, 7.55430502e-312],
       [2.54639495e-312, 1.59089138e-321,             nan,
        2.58883486e-312, 6.36598749e-314],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 6.89841916e-310, 6.89841916e-310,
        4.66349696e-310

In [71]:
matriz8 = np.tile(np.array([[1,2], [3,4], [5,6]]), 2)  # Repete os valores no número de vezes determinado ao final.
matriz8

array([[1, 2, 1, 2],
       [3, 4, 3, 4],
       [5, 6, 5, 6]])

In [72]:
matriz9 = np.tile(np.array([[1,2], [3,4], [5,6]]), (3,4)) # Repete os valores no número de vezes determinado ao final.
matriz9

array([[1, 2, 1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4, 3, 4],
       [5, 6, 5, 6, 5, 6, 5, 6],
       [1, 2, 1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4, 3, 4],
       [5, 6, 5, 6, 5, 6, 5, 6],
       [1, 2, 1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4, 3, 4],
       [5, 6, 5, 6, 5, 6, 5, 6]])