In [1]:
import numpy as np

In [4]:
a = np.array([-10, 10, 20, 30], dtype='float')  # Passando um tipo(float) para o array.

In [5]:
a

array([-10.,  10.,  20.,  30.])

In [6]:
a.dtype  # mostra o tipo do array.

dtype('float64')

In [7]:
b = np.array([-10, 10, 20, 30])

In [8]:
b.dtype

dtype('int64')

In [10]:
c = np.array(['Rodrigo', 10, 5.5])

In [13]:
c.dtype

dtype('<U7')

In [16]:
d = np.array([True, False])  # Tipo boleano.

In [15]:
d.dtype

dtype('bool')

In [17]:
e = np.array([10,20,30.5])

In [18]:
e.dtype

dtype('float64')

In [20]:
e.astype(int)  # Converte o tipo do array.

array([10, 20, 30])

In [23]:
f = np.arange(0,10)  # Cria um array utilizando o range definido.

In [24]:
f

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
g = np.arange(0, 10) * 10  # Cria um array já multiplicando. Se usar ** eleva a potencia definida.

In [38]:
g

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

# Operações aritméticas com arrays

In [39]:
arrayA = np.arange(0,10)
arrayB = np.arange(1,11)

In [40]:
arrayA

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
arrayB

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [42]:
arrayA + arrayB

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [43]:
arrayA * arrayB

array([ 0,  2,  6, 12, 20, 30, 42, 56, 72, 90])

In [45]:
arrayB - arrayA

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [46]:
# Comparação
arrayA == arrayB

array([False, False, False, False, False, False, False, False, False,
       False])

In [47]:
arrayA > arrayB

array([False, False, False, False, False, False, False, False, False,
       False])

In [48]:
arrayA < arrayB

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [56]:
# Comparar arrays usando lógica booleana.
array1 = np.array([False, False, True, False])
array2 = np.array([False, True, True, False])
np.logical_and(array1,array2)

array([False, False,  True, False])

In [57]:
np.logical_or(array1, array2)

array([False,  True,  True, False])

## Para operações com arrays, eles tem que ser do mesmo tamanho.

In [ ]:
arrayC = np.array([1, 2, 3])
arrayD = np.array([1, 2])
arrayC + arrayD                      # Não é possível fazer esse tipo de operação.

## Dot Product

In [62]:
arrayE = np.array([1, 2, 3])
arrayF = np.array([2, 4, 6])
# A operação abaixo é conhecida como 'HADAMARD PRODUCT'
arrayE * arrayF   

array([ 2,  8, 18])

In [65]:
# Essa é a operação 'DOT PRODUCT' ou 'SCALAR PRODUCT'
np.dot(arrayE, arrayF)  # A diferença é que ele soma o resultado do produto: 18+8+2

28

## Para copiar um array, utilize a função .copy(), senão é gerado somente um link.

In [66]:
a = np.array([1, 2, 3, 4, 5])

In [67]:
b = a   # Somente um link

In [68]:
c = np.array([1, 2, 3, 4, 5])

In [69]:
d = a[3:].copy()  # Cria uma cópia do array sem nenhum link.

In [70]:
d

array([4, 5])