In [4]:
import numpy as np

In [11]:
ar = np.array([[1,2, 3], [4,5,6], [7,8,9]])

In [12]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
print(ar[-1])

[7 8 9]


In [26]:
at = np.array([['a',1,2,3,], ['b',4,5,6], ['c',7,8,9]])
print(at)

[['a' '1' '2' '3']
 ['b' '4' '5' '6']
 ['c' '7' '8' '9']]


In [27]:
print(at[:,0])

['a' 'b' 'c']


In [28]:
print(at[1:3,1:3])

[['4' '5']
 ['7' '8']]


In [29]:
a = np.array([[1,2], [3,4]])
b = np.array([[5,6]])

In [30]:
x = np.concatenate([a,b])

In [31]:
x

array([[1, 2],
       [3, 4],
       [5, 6]])